### ISSUE TITLE
tibet build needed in quickstart tl;dr

### ISSUE THREAD

**Issue by jabowery** [TechnicalPursuit/TIBET#281]
https://www.technicalpursuit.com/docs/quickstart.html

Needs a `tibet build` in:

```
# Create a new project, initialize it, and start the development server.
$ cd /tmp   # or a suitable temporary directory
$ tibet clone hello
$ cd hello
$ tibet init
$ tibet start
```

Although the `#?boot.profile=development` apparently works without it, the `TDS` log message "Project not built..." leads one to suspect that it is needed.  Moreover, without the URL argument, it does fail.

Other nits:

The directions to "Edit..." should probably say "Replace the contents of...with:"

After that, it probably does bear saying to refresh the browser because, at least on my Chrome browser, updating the files didn't refresh.

**Comment by bedney** [comment]
Jim -

Thanks for the report.

We're trying to make the initial 'up and running' process as streamlined as possible, which is why we omitted the `tibet build` before folks fire up their app (the assumption was that they would be doing development first). We should maybe make it more clear that they should be running the 'developer' URL as a 'first time' thing.

Also, I'm curious as to why updating the files didn't refresh. Were you running in developer mode? If not, they won't automatically refresh in production mode (the argument-less URL).

Thanks!

Cheers,

- Bill

**Comment by idearat** [comment]
Migrated to GitLab.
