### ISSUE TITLE
getWindowById fails on SCREEN_0, which is UICANVAS

### ISSUE THREAD

**Issue by idearat** [TechnicalPursuit/TIBET#502]
the getWindowById call fails to find windows that exist by their "name" property (which is how most of us think of the window ID).

`TP.sys.getWindowById('SCREEN_0')` should work.

**Comment by bedney** [comment]
So since `SCREEN_0` is really hardcoding the ui canvas window into your path, you don't want to do that (`SCREEN_0` only exists in a Lama-enabled world). Use `TP.sys.getUICanvas()` instead, which returns a TP.core.Window (or `TP.sys.getUICanvas(true)` to return an unwrapped Window). I did patch the `TP.sys.getWindowById` call so that you can also say `TP.sys.getWindowById('UICANVAS')` using the literal `UICANVAS` so you can use that as well.
